src/assets/css/reset.css, src/components/main/indexBottom.jsx, src/components/main/indexTop.jsx, src/pages/index.jsx, src/path/path.jsx
header 수정했습니다.
button props에 참, 거짓을 넣으면 작동합니다.
=> Feature 임동현

src/components/button/buttonPrimary/buttonPrimary56/buttonPrimary56.jsx, src/components/chooseBackground/chooseBackground.jsx
데이터를 잘 못 다뤄서 페이지 이동 간 오류 발생 해결
=> post 페이지 오류 수정

src/components/button/buttonPrimary/buttonPrimary56/buttonPrimary56.jsx, src/pages/list/index.jsx, src/path/path.jsx
페이지 이동 버튼 잘 동작합니다
post/{id} 페이지 미 구현
=> feat: list, post, post{id} 페이지 이동

src/components/button/buttonPrimary/buttonPrimary56/buttonPrimary56.jsx, src/pages/post/id/index.jsx, src/path/path.jsx, src/store/recoil/apiData.jsx
post 페이지에서 버튼 누르면 post/{id} 페이지 이동
=> feat: /post/{id} 페이지 이동

src/components/inputName/inputName.css
- inputName 간격 수정
- css 수정 했습니다.
=> fix: inputName 간격 수정

package-lock.json, src/components/inputName/inputName.css, src/components/textField/input/textInput.css, src/components/textField/input/textInput.jsx
- input 에러 메시지 스크립트 완료
- input에서 값이 없을때 focusOut 하면 에러메시지 생성
=> feat: input 에러 메시지 스크립트

package-lock.json, package.json, src/apis/messageApi.jsx, src/components/button/buttonOutlined/buttonOutlined40/buttonOutlined40.css, src/components/button/buttonOutlined/buttonOutlined40/buttonOutlined40.jsx, src/components/postId/PostidNav.jsx, src/components/postId/PostidNav.module.css, src/components/postId/emojiModal/emojiModal.jsx, src/pages/post/id/index.jsx, src/store/recoil/apiData.jsx
- post/id 페이지의 topnav에서 이모지 라이브러리 적용과 이모지 추가 기능 구현
- post/id 페이지에서 이모지 라이브러리 적용
- 원하는 이모지를 클릭할 시 해당 이모지 postApi 수행
- 이모지 추가 버튼을 열고 닫을 때 이모지 보여주는 부분 리로딩 되어 상태변경 적용
- ButtonOutlined40 의 props 부분과 내부 코드 수정
=> feat: post/id 페이지 이모지 추가 기능 구현

package-lock.json, package.json, src/components/button/buttonPrimary/buttonPrimary56/buttonPrimary56.jsx, src/components/chooseBackground/chooseBackground.jsx, src/components/rollingPaper/rollingPaperBox/profileImg/profileImg.css, src/components/rollingPaper/rollingPaperBox/profileImg/profileImg.jsx, src/components/rollingPaper/rollingPaperBox/rollingPaperBox.css, src/components/rollingPaper/rollingPaperBox/rollingPaperBox.jsx, src/components/rollingPaper/rollingPaperList/rollingPaperList.jsx, src/pages/list/index.css, src/pages/list/index.jsx
- 배경화면 이미지도 나오게 수정
- 배경화면 색상만 나왔었는데, 이미지도 출력 되게 수정함
=> fix: 롤링페이퍼 배경화면 이미지 나오게 수정

src/components/postId/PostidNav.jsx, src/components/postId/PostidNav.module.css
- post/id 페이지 이모지추가 모달 수정
- 이모지 추가하는 모달 z index 추가
=> fix: post/id 페이지 이모지추가 모달 수정

public/images/search_icon.svg, src/assets/css/reset.css, src/components/header/header.css, src/components/header/header.jsx, src/components/search/searchContents.css, src/components/search/searchContents.jsx, src/pages/search/index.jsx, src/path/path.jsx, src/store/recoil/apiData.jsx
- 검색 기능 완료했습니다.
- header에 검색 아이콘을 넣고 메시지 입력 후 엔터 하면 이동합니다.
=> feat: 검색 기능 완료

src/components/chooseBackground/chooseBackground.jsx, src/components/postId/PostidBody.jsx, src/components/postId/PostidBody.module.css, src/components/postId/PostidNav.jsx, src/components/postId/messageBox/messageBox.css, src/components/postId/messageBox/messageBox.jsx, src/components/search/searchContents.jsx, src/components/textField/input/textInput.jsx, src/pages/post/id/index.jsx, src/utils/utilsFunction.js
- post/id 페이지 message 구현 완료
- post/id 페이지 message 구현 완료했습니다.
- 클릭시 나오는 modal과 배경화면은 아직 구현하지 못했습니다.
=> feat: post/id 페이지 message 구현 완료

src/components/button/buttonPrimary/buttonPrimary56/buttonPrimary56.jsx, src/components/postId/PostidBody.jsx, src/components/postId/PostidBody.module.css, src/components/postId/messageBox/messageBox.css, src/components/postId/messageBox/messageBox.jsx, src/pages/index.jsx, src/pages/post/id/edit/index.jsx
- 수정, 삭제 버튼 기능 보완
- 수정 버튼 누르면 edit 페이지로 이동
- 삭제 버튼 누르면 페이지 삭제 후 메인페이지로 이동
=> feat: 수정, 삭제 버튼 기능 보완

src/components/postId/PostidBody.module.css, src/pages/list/index.jsx
- 나도 만들어보기 버튼 링크 수정
- 나도 만들어보기 버튼 링크 수정
=> fix: 나도 만들어보기 버튼 링크 수정

src/components/rollingPaper/rollingPaperBox/rollingPaperBox.jsx, src/components/rollingPaper/rollingPaperBox/rollingPaperBox.module.css
- list페이지 완성
- list 페이지 기능 동작 및 디자인 구현 완료
=> feat: list 페이지 완성

src/assets/css/reset.css, src/components/button/buttonOutlined/buttonOutlined40/buttonOutlined40.css, src/components/postId/PostNav.css, src/components/postId/PostidBody.module.css, src/components/postId/PostidNav.jsx, src/components/postId/PostidNav.module.css, src/components/postId/emojiAddModal/emojiAddModal.jsx, src/components/postId/emojiShowModal/emojiShowModal.module.css, src/components/postId/messageModal/messageModal.jsx, src/components/postId/messageModal/messageModal.module.css, src/components/profileList/profileImg/profileImg.module.css, src/components/reaction/Reaction.css, src/components/rollingPaper/rollingPaperList/rollingPaperList.css, src/components/rollingPaper/rollingPaperList/rollingPaperList.jsx
- 반응형 구현 & 스타일 수정
- 반응형 구현 & 스타일 수정했습니다.
=> fix: 반응형 구현 & 스타일 수정

src/components/background/backgroundColor/backgroundColor.css, src/components/background/backgroundColor/backgroundColor.jsx, src/components/background/backgroundImg/backgroundImg.css, src/components/background/backgroundImg/backgroundImg.jsx, src/components/chooseBackground/chooseBackground.css, src/components/postId/PostidBody.jsx, src/components/postId/PostidBody.module.css, src/components/postId/messageBox/messageBox.css, src/components/postId/messageBox/messageBox.jsx, src/components/toggleButton/toggleButton.css, src/components/toggleButton/toggleButton.jsx, src/pages/notFound/index.jsx, src/pages/notFound/index.module.css, src/pages/post/id/index.jsx, src/pages/post/index.jsx, src/pages/post/index.module.css, src/path/path.jsx
- 라우터 notFound 페이지와 post 반응형 동작
- 잘못된 경로는 notFound페이지 처리 및 post 마우스 호버시 반응형 동작 작업
=> fix: 라우터 수정 및 post 반응형 웹 페이지

src/components/header/header.jsx, src/components/postId/PostidNav.jsx, src/components/postId/emojiAddModal/emojiAddModal.jsx, src/components/postId/emojiShowModal/emojiShowModal.jsx, src/store/recoil/apiData.jsx
- 모달 영역 외 클릭시 닫힘
- 검색 모달 상시 열려있는 동작 수정
- post/id 페이지 모달 영역 외 클릭시 모달 닫힘 구현
=> Feature document target

src/components/postId/PostidNav.jsx
- 등록된 이모지 없을때 최대 8개의 이모지를 보여주는 모달 토글버튼이 보이지 않도록 구현
-
=> feat: 이모지 0개일 때 ui 다르게 보이도록

src/components/postId/PostidBody.jsx, src/components/postId/PostidNav.jsx, src/pages/post/id/edit/index.jsx, src/pages/post/id/index.jsx
=> fix: edit 페이지 카드 삭제시 명 수 변경

package-lock.json, src/apis/apiRecipient.jsx, src/components/postId/PostidBody.jsx, src/pages/list/index.jsx, src/store/recoil/apiData.jsx
- 삭제 기능 수정
- 삭제 기능 수정했습니다. 해당 코드 주석으로 보시면 됩니다.
=> fix: 삭제 기능 수정

src/components/postId/PostidBody.module.css, src/components/postId/PostidNav.jsx, src/components/postId/PostidNav.module.css, src/components/postId/emojiShowModal/emojiShowModal.module.css, src/components/reaction/Reaction.module.css, src/components/textField/dropdown/textDropdown.jsx
=> fix: 스타일 수정

index.html, src/components/background/backgroundImg/backgroundImg.jsx, src/components/toggleButton/toggleButton.jsx
- index.html en > ko 수정 및 post페이지 배경화면 초기값 수정
- index.html en > ko 수정 및 post페이지 배경화면 초기값 수정
=> 1.2 버그 수정 최종 완성본

src/components/postId/PostidBody.jsx, src/components/postId/PostidBody.module.css
- post/id 페이지 height 수정
- post/id 페이지에 배경 화면이 잘려서 height 수정했습니다.
=> fix: post/id 페이지 height 수정
